// Code generated by Kitex v0.2.1. DO NOT EDIT.

package chartservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/huolunl/nika-component-base/pkg/nika_api/nika_chartmuseum/v1/kitex_gen/nika_chartmuseum"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler nika_chartmuseum.ChartService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
