// Code generated by Kitex v0.2.1. DO NOT EDIT.
package nikaapplication

import (
	"github.com/cloudwego/kitex/server"
	"github.com/huolunl/nika-component-base/pkg/nika_api/nika_application/v1/kitex_gen/nika_application"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler nika_application.NikaApplication, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
