// Code generated by Kitex v0.2.1. DO NOT EDIT.

package nikacluster

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/huolunl/nika-component-base/pkg/nika_api/nika_cluster/v1/kitex_gen/nika_cluster"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateCluster(ctx context.Context, Req *nika_cluster.CreateClusterRequest, callOptions ...callopt.Option) (r *nika_cluster.CreateClusterResponse, err error)
	GetCluster(ctx context.Context, Req *nika_cluster.GetClusterRequest, callOptions ...callopt.Option) (r *nika_cluster.GetClusterResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kNikaClusterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNikaClusterClient struct {
	*kClient
}

func (p *kNikaClusterClient) CreateCluster(ctx context.Context, Req *nika_cluster.CreateClusterRequest, callOptions ...callopt.Option) (r *nika_cluster.CreateClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCluster(ctx, Req)
}

func (p *kNikaClusterClient) GetCluster(ctx context.Context, Req *nika_cluster.GetClusterRequest, callOptions ...callopt.Option) (r *nika_cluster.GetClusterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCluster(ctx, Req)
}
