// Code generated by Kitex v0.2.0. DO NOT EDIT.
package nikauser

import (
	"github.com/cloudwego/kitex/server"
	"github.com/huolunl/nika-component-base/pkg/nika_api/nika_user/v1/kitex_gen/nika_user"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler nika_user.NikaUser, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
